/**
 * Manufacturing job-function taxonomy (D10 — docs/guides/01-library-artifactory.md §3).
 *
 * Mechanically converted from `docs/research/oem-job-taxonomy.md` §3 (20
 * function families, ~250 job types across an automated OEM — Design Studio
 * through Business Services). Each entry's `key` is a stable snake_case slug
 * derived from the job title; `aliases` carry parenthetical
 * abbreviations/synonyms (e.g. "PQE") and slash-separated alternate titles so
 * the questionnaire (`client` module) can map free-text choices onto these
 * keys. `headcountWeight` is a relative sizing hint (fixture data, not a real
 * customer metric) — operator/technician roles weighted highest, leadership
 * lowest — used by `packages/discovery`'s gap analysis to rank uncovered job
 * functions.
 *
 * Two entries at the end (`general_office_staff`, `executive_assistant`) are
 * hand-curated additions NOT present in the OEM engineering-heavy research
 * sweep — every real OEM also has general office staff and executive
 * assistants, and the existing pilot work packages (`office_worker_general`,
 * `exec_assistant`) need a job-function key to resolve against.
 *
 * Kept as a same-package sibling module (not a separate @arm/* package) —
 * `packages/profiles` stays a leaf package with zero cross-package imports;
 * this file only decomposes manufacturing.profile.ts for readability.
 */

import type { JobFunctionSeed } from "./types.js";

export const MANUFACTURING_JOB_FUNCTIONS: JobFunctionSeed[] = [
  { key: "exterior_designer", name: "Exterior Designer", functionFamily: "Design Studio", aliases: ["exterior designer"], headcountWeight: 10 },
  { key: "interior_designer", name: "Interior Designer", functionFamily: "Design Studio", aliases: ["interior designer"], headcountWeight: 10 },
  { key: "cmf_designer_color_material_finish", name: "CMF Designer (Color/Material/Finish)", functionFamily: "Design Studio", aliases: ["cmf designer", "cmf designer (color/material/finish)", "color/material/finish"], headcountWeight: 10 },
  { key: "digital_sculptor_class_a_modeler", name: "Digital Sculptor / Class-A Modeler", functionFamily: "Design Studio", aliases: ["class-a modeler", "digital sculptor", "digital sculptor / class-a modeler"], headcountWeight: 10 },
  { key: "clay_modeler", name: "Clay Modeler", functionFamily: "Design Studio", aliases: ["clay modeler"], headcountWeight: 10 },
  { key: "ux_hmi_designer", name: "UX/HMI Designer", functionFamily: "Design Studio", aliases: ["hmi designer", "ux", "ux/hmi designer"], headcountWeight: 10 },
  { key: "packaging_engineer_vehicle_integration", name: "Packaging Engineer (Vehicle Integration)", functionFamily: "Design Studio", aliases: ["packaging engineer", "packaging engineer (vehicle integration)", "vehicle integration"], headcountWeight: 14 },
  { key: "design_director_chief_designer", name: "Design Director / Chief Designer", functionFamily: "Design Studio", aliases: ["chief designer", "design director", "design director / chief designer"], headcountWeight: 4 },
  { key: "research_scientist_materials", name: "Research Scientist (Materials)", functionFamily: "R&D & Advanced Engineering", aliases: ["materials", "research scientist", "research scientist (materials)"], headcountWeight: 14 },
  { key: "advanced_powertrain_engineer", name: "Advanced Powertrain Engineer", functionFamily: "R&D & Advanced Engineering", aliases: ["advanced powertrain engineer"], headcountWeight: 14 },
  { key: "adas_autonomous_driving_engineer", name: "ADAS / Autonomous Driving Engineer", functionFamily: "R&D & Advanced Engineering", aliases: ["adas", "adas / autonomous driving engineer", "autonomous driving engineer"], headcountWeight: 14 },
  { key: "ai_ml_research_engineer", name: "AI/ML Research Engineer", functionFamily: "R&D & Advanced Engineering", aliases: ["ai", "ai/ml research engineer", "ml research engineer"], headcountWeight: 14 },
  { key: "nvh_specialist_r_d", name: "NVH Specialist (R&D)", functionFamily: "R&D & Advanced Engineering", aliases: ["nvh specialist", "nvh specialist (r&d)", "r&d"], headcountWeight: 14 },
  { key: "patent_engineer_ip_analyst", name: "Patent Engineer / IP Analyst", functionFamily: "R&D & Advanced Engineering", aliases: ["ip analyst", "patent engineer", "patent engineer / ip analyst"], headcountWeight: 14 },
  { key: "technology_scout", name: "Technology Scout", functionFamily: "R&D & Advanced Engineering", aliases: ["technology scout"], headcountWeight: 10 },
  { key: "chief_engineer_program_leader", name: "Chief Engineer / Program Leader", functionFamily: "Product Engineering (Design-Release)", aliases: ["chief engineer", "chief engineer / program leader", "program leader"], headcountWeight: 14, marketTier: "neighboring" },
  { key: "design_release_engineer", name: "Design Release Engineer (PD-DRE)", functionFamily: "Product Engineering (Design-Release)", aliases: ["design release engineer", "dre", "pd-dre"], headcountWeight: 14, marketTier: "neighboring" },
  { key: "systems_engineer", name: "Systems Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["systems engineer"], headcountWeight: 14 },
  { key: "component_design_engineer", name: "Component Design Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["component design engineer"], headcountWeight: 14 },
  { key: "e_e_architecture_engineer", name: "E/E Architecture Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["e", "e architecture engineer", "e/e architecture engineer"], headcountWeight: 14 },
  { key: "ecu_hardware_design_engineer", name: "ECU Hardware Design Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["ecu hardware design engineer"], headcountWeight: 14 },
  { key: "wiring_harness_engineer", name: "Wiring Harness Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["wiring harness engineer"], headcountWeight: 14 },
  { key: "embedded_software_engineer", name: "Embedded Software Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["embedded software engineer"], headcountWeight: 14 },
  { key: "model_based_controls_algorithm_engineer", name: "Model-Based Controls / Algorithm Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["algorithm engineer", "model-based controls", "model-based controls / algorithm engineer"], headcountWeight: 14 },
  { key: "autosar_bsw_mcal_integration_engineer", name: "AUTOSAR BSW / MCAL Integration Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["autosar bsw", "autosar bsw / mcal integration engineer", "mcal integration engineer"], headcountWeight: 14 },
  { key: "functional_safety_engineer_iso_26262", name: "Functional Safety Engineer (ISO 26262)", functionFamily: "Product Engineering (Design-Release)", aliases: ["functional safety engineer", "functional safety engineer (iso 26262)", "iso 26262"], headcountWeight: 14 },
  { key: "embedded_cybersecurity_engineer_iso_21434_unece_r155", name: "Embedded Cybersecurity Engineer (ISO 21434 / UNECE R155)", functionFamily: "Product Engineering (Design-Release)", aliases: ["embedded cybersecurity engineer", "embedded cybersecurity engineer (iso 21434 / unece r155)", "iso 21434 / unece r155"], headcountWeight: 14 },
  { key: "diagnostics_ota_bootloader_engineer", name: "Diagnostics / OTA / Bootloader Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["bootloader engineer", "diagnostics", "diagnostics / ota / bootloader engineer", "ota"], headcountWeight: 14 },
  { key: "cad_designer_drafter", name: "CAD Designer / Drafter", functionFamily: "Product Engineering (Design-Release)", aliases: ["cad designer", "cad designer / drafter", "drafter"], headcountWeight: 10 },
  { key: "plm_bom_engineer", name: "PLM / BOM Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["bom engineer", "plm", "plm / bom engineer"], headcountWeight: 14 },
  { key: "dmu_engineer", name: "DMU Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["dmu engineer"], headcountWeight: 14 },
  { key: "cost_engineer_target_costing", name: "Cost Engineer (Target Costing)", functionFamily: "Product Engineering (Design-Release)", aliases: ["cost engineer", "cost engineer (target costing)", "target costing"], headcountWeight: 14 },
  { key: "joining_fastener_engineer", name: "Joining / Fastener Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["fastener engineer", "joining", "joining / fastener engineer"], headcountWeight: 14 },
  { key: "materials_lightweighting_engineer", name: "Materials & Lightweighting Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["materials & lightweighting engineer"], headcountWeight: 14 },
  { key: "emc_engineer", name: "EMC Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["emc engineer"], headcountWeight: 14 },
  { key: "signal_power_integrity_engineer", name: "Signal/Power Integrity Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["power integrity engineer", "signal", "signal/power integrity engineer"], headcountWeight: 14 },
  { key: "power_electronics_engineer", name: "Power Electronics Engineer", functionFamily: "Product Engineering (Design-Release)", aliases: ["power electronics engineer"], headcountWeight: 14 },
  { key: "fea_structural_analyst", name: "FEA Structural Analyst", functionFamily: "CAE / Simulation", aliases: ["fea structural analyst"], headcountWeight: 14 },
  { key: "cfd_aero_engineer", name: "CFD / Aero Engineer", functionFamily: "CAE / Simulation", aliases: ["aero engineer", "cfd", "cfd / aero engineer"], headcountWeight: 14 },
  { key: "crash_occupant_safety_analyst", name: "Crash & Occupant Safety Analyst", functionFamily: "CAE / Simulation", aliases: ["crash & occupant safety analyst"], headcountWeight: 14 },
  { key: "durability_fatigue_analyst", name: "Durability & Fatigue Analyst", functionFamily: "CAE / Simulation", aliases: ["durability & fatigue analyst"], headcountWeight: 14 },
  { key: "nvh_analyst", name: "NVH Analyst", functionFamily: "CAE / Simulation", aliases: ["nvh analyst"], headcountWeight: 14 },
  { key: "thermal_systems_engineer", name: "Thermal Systems Engineer", functionFamily: "CAE / Simulation", aliases: ["thermal systems engineer"], headcountWeight: 14 },
  { key: "multibody_dynamics_mbd_engineer", name: "Multibody Dynamics (MBD) Engineer", functionFamily: "CAE / Simulation", aliases: ["mbd", "multibody dynamics  engineer", "multibody dynamics (mbd) engineer"], headcountWeight: 14 },
  { key: "electromagnetic_motor_analyst", name: "Electromagnetic / Motor Analyst", functionFamily: "CAE / Simulation", aliases: ["electromagnetic", "electromagnetic / motor analyst", "motor analyst"], headcountWeight: 14 },
  { key: "1d_systems_simulation_engineer", name: "1D Systems Simulation Engineer", functionFamily: "CAE / Simulation", aliases: ["1d systems simulation engineer"], headcountWeight: 14 },
  { key: "simulation_data_management_sdm_engineer", name: "Simulation Data Management (SDM) Engineer", functionFamily: "CAE / Simulation", aliases: ["sdm", "simulation data management  engineer", "simulation data management (sdm) engineer"], headcountWeight: 14 },
  { key: "hil_test_engineer", name: "HIL Test Engineer", functionFamily: "Test & Validation", aliases: ["hil test engineer"], headcountWeight: 14 },
  { key: "sil_mil_test_engineer", name: "SIL / MIL Test Engineer", functionFamily: "Test & Validation", aliases: ["mil test engineer", "sil", "sil / mil test engineer"], headcountWeight: 14 },
  { key: "durability_road_load_data_engineer", name: "Durability / Road-Load Data Engineer", functionFamily: "Test & Validation", aliases: ["durability", "durability / road-load data engineer", "road-load data engineer"], headcountWeight: 14 },
  { key: "component_bench_test_engineer", name: "Component / Bench Test Engineer", functionFamily: "Test & Validation", aliases: ["bench test engineer", "component", "component / bench test engineer"], headcountWeight: 14 },
  { key: "powertrain_calibration_engineer", name: "Powertrain Calibration Engineer", functionFamily: "Test & Validation", aliases: ["powertrain calibration engineer"], headcountWeight: 14 },
  { key: "homologation_certification_engineer", name: "Homologation / Certification Engineer", functionFamily: "Test & Validation", aliases: ["certification engineer", "homologation", "homologation / certification engineer"], headcountWeight: 14 },
  { key: "instrumentation_daq_engineer", name: "Instrumentation / DAQ Engineer", functionFamily: "Test & Validation", aliases: ["daq engineer", "instrumentation", "instrumentation / daq engineer"], headcountWeight: 14 },
  { key: "field_fleet_test_engineer", name: "Field / Fleet Test Engineer", functionFamily: "Test & Validation", aliases: ["field", "field / fleet test engineer", "fleet test engineer"], headcountWeight: 14 },
  { key: "crash_safety_test_engineer", name: "Crash/Safety Test Engineer", functionFamily: "Test & Validation", aliases: ["crash", "crash/safety test engineer", "safety test engineer"], headcountWeight: 14 },
  { key: "nvh_test_engineer", name: "NVH Test Engineer", functionFamily: "Test & Validation", aliases: ["nvh test engineer"], headcountWeight: 14 },
  { key: "environmental_test_engineer", name: "Environmental Test Engineer", functionFamily: "Test & Validation", aliases: ["environmental test engineer"], headcountWeight: 14 },
  { key: "prototype_build_engineer", name: "Prototype Build Engineer", functionFamily: "Test & Validation", aliases: ["prototype build engineer"], headcountWeight: 14 },
  { key: "requirements_engineer", name: "Requirements Engineer", functionFamily: "Systems Engineering / MBSE", aliases: ["requirements engineer"], headcountWeight: 14 },
  { key: "mbse_model_architect", name: "MBSE / Model Architect", functionFamily: "Systems Engineering / MBSE", aliases: ["mbse", "mbse / model architect", "model architect"], headcountWeight: 8 },
  { key: "functional_safety_compliance_systems_engineer", name: "Functional Safety & Compliance Systems Engineer", functionFamily: "Systems Engineering / MBSE", aliases: ["functional safety & compliance systems engineer"], headcountWeight: 14 },
  { key: "system_integration_engineer", name: "System Integration Engineer", functionFamily: "Systems Engineering / MBSE", aliases: ["system integration engineer"], headcountWeight: 14 },
  { key: "additive_manufacturing_engineer", name: "Additive Manufacturing Engineer", functionFamily: "Prototyping, Additive & Tooling", aliases: ["additive manufacturing engineer"], headcountWeight: 14 },
  { key: "model_shop_rapid_prototyping_technician", name: "Model Shop / Rapid Prototyping Technician", functionFamily: "Prototyping, Additive & Tooling", aliases: ["model shop", "model shop / rapid prototyping technician", "rapid prototyping technician"], headcountWeight: 45 },
  { key: "tool_die_design_engineer", name: "Tool & Die Design Engineer", functionFamily: "Prototyping, Additive & Tooling", aliases: ["tool & die design engineer"], headcountWeight: 14 },
  { key: "moldflow_analyst", name: "Moldflow Analyst", functionFamily: "Prototyping, Additive & Tooling", aliases: ["moldflow analyst"], headcountWeight: 14 },
  { key: "sheet_metal_forming_simulation_engineer", name: "Sheet-Metal Forming Simulation Engineer", functionFamily: "Prototyping, Additive & Tooling", aliases: ["sheet-metal forming simulation engineer"], headcountWeight: 14 },
  { key: "tool_tryout_correction_engineer", name: "Tool Tryout / Correction Engineer", functionFamily: "Prototyping, Additive & Tooling", aliases: ["correction engineer", "tool tryout", "tool tryout / correction engineer"], headcountWeight: 14 },
  { key: "fixture_gauge_design_engineer", name: "Fixture / Gauge Design Engineer", functionFamily: "Prototyping, Additive & Tooling", aliases: ["fixture", "fixture / gauge design engineer", "gauge design engineer"], headcountWeight: 14 },
  { key: "cnc_programmer", name: "CNC Programmer", functionFamily: "CAM / CNC Programming", aliases: ["cnc programmer"], headcountWeight: 14 },
  { key: "multi_axis_machining_specialist", name: "Multi-Axis Machining Specialist", functionFamily: "CAM / CNC Programming", aliases: ["multi-axis machining specialist"], headcountWeight: 14 },
  { key: "machining_simulation_verification_engineer", name: "Machining Simulation / Verification Engineer", functionFamily: "CAM / CNC Programming", aliases: ["machining simulation", "machining simulation / verification engineer", "verification engineer"], headcountWeight: 14 },
  { key: "post_processor_developer", name: "Post-Processor Developer", functionFamily: "CAM / CNC Programming", aliases: ["post-processor developer"], headcountWeight: 14 },
  { key: "cmm_metrology_programmer", name: "CMM / Metrology Programmer", functionFamily: "CAM / CNC Programming", aliases: ["cmm", "cmm / metrology programmer", "metrology programmer"], headcountWeight: 14 },
  { key: "process_engineer_stamping_body_weld_paint_assembly", name: "Process Engineer (Stamping/Body/Weld/Paint/Assembly)", functionFamily: "Manufacturing Engineering / Process", aliases: ["process engineer", "process engineer (stamping/body/weld/paint/assembly)", "stamping/body/weld/paint/assembly"], headcountWeight: 14 },
  { key: "industrial_engineer", name: "Industrial Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["industrial engineer"], headcountWeight: 14 },
  { key: "automation_controls_engineer", name: "Automation / Controls Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["automation", "automation / controls engineer", "controls engineer"], headcountWeight: 14 },
  { key: "robotics_cell_engineer", name: "Robotics Cell Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["robotics cell engineer"], headcountWeight: 14 },
  { key: "tooling_engineer_dies_fixtures", name: "Tooling Engineer (Dies & Fixtures)", functionFamily: "Manufacturing Engineering / Process", aliases: ["dies & fixtures", "tooling engineer", "tooling engineer (dies & fixtures)"], headcountWeight: 14 },
  { key: "factory_simulation_engineer", name: "Factory Simulation Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["factory simulation engineer"], headcountWeight: 14 },
  { key: "manufacturing_it_mes_engineer", name: "Manufacturing IT / MES Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["manufacturing it", "manufacturing it / mes engineer", "mes engineer"], headcountWeight: 14 },
  { key: "launch_program_manager_apqp", name: "Launch / Program Manager (APQP)", functionFamily: "Manufacturing Engineering / Process", aliases: ["apqp", "launch", "launch / program manager (apqp)", "program manager", "project manager"], headcountWeight: 8, marketTier: "neighboring" },
  { key: "dfm_dfa_engineer", name: "DfM / DfA Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["dfa engineer", "dfm", "dfm / dfa engineer"], headcountWeight: 14 },
  { key: "bop_mbom_engineer", name: "BOP / MBOM Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["bop", "bop / mbom engineer", "mbom engineer"], headcountWeight: 14 },
  { key: "assembly_process_planner", name: "Assembly Process Planner", functionFamily: "Manufacturing Engineering / Process", aliases: ["assembly process planner"], headcountWeight: 14 },
  { key: "ecn_change_management_coordinator", name: "ECN / Change Management Coordinator", functionFamily: "Manufacturing Engineering / Process", aliases: ["change management coordinator", "ecn", "ecn / change management coordinator"], headcountWeight: 14 },
  { key: "dimensional_management_engineer", name: "Dimensional Management Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["dimensional management engineer"], headcountWeight: 14 },
  { key: "welding_joints_process_engineer", name: "Welding / Joints Process Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["joints process engineer", "welding", "welding / joints process engineer"], headcountWeight: 14 },
  { key: "paint_coating_process_engineer", name: "Paint / Coating Process Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["coating process engineer", "paint", "paint / coating process engineer"], headcountWeight: 14 },
  { key: "electrification_battery_process_engineer", name: "Electrification / Battery Process Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["battery process engineer", "electrification", "electrification / battery process engineer"], headcountWeight: 14 },
  { key: "ergonomics_human_factors_engineer", name: "Ergonomics / Human Factors Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["ergonomics", "ergonomics / human factors engineer", "human factors engineer"], headcountWeight: 14 },
  { key: "throughput_discrete_event_simulation_engineer", name: "Throughput / Discrete-Event Simulation Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["discrete-event simulation engineer", "throughput", "throughput / discrete-event simulation engineer"], headcountWeight: 14 },
  { key: "material_flow_internal_logistics_engineer", name: "Material Flow / Internal Logistics Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["internal logistics engineer", "material flow", "material flow / internal logistics engineer"], headcountWeight: 14 },
  { key: "robot_simulation_olp_engineer", name: "Robot Simulation / OLP Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["olp engineer", "robot simulation", "robot simulation / olp engineer"], headcountWeight: 14 },
  { key: "digital_twin_virtual_commissioning_engineer", name: "Digital Twin / Virtual Commissioning Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["digital twin", "digital twin / virtual commissioning engineer", "virtual commissioning engineer"], headcountWeight: 14 },
  { key: "smart_factory_iiot_engineer", name: "Smart Factory / IIoT Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["iiot engineer", "smart factory", "smart factory / iiot engineer"], headcountWeight: 14 },
  { key: "agv_amr_systems_engineer", name: "AGV / AMR Systems Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["agv", "agv / amr systems engineer", "amr systems engineer"], headcountWeight: 14 },
  { key: "factory_layout_greenfield_planning_engineer", name: "Factory Layout / Greenfield Planning Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["factory layout", "factory layout / greenfield planning engineer", "greenfield planning engineer"], headcountWeight: 14 },
  { key: "plm_administrator", name: "PLM Administrator", functionFamily: "Manufacturing Engineering / Process", aliases: ["plm administrator"], headcountWeight: 14 },
  { key: "cad_administrator_customization", name: "CAD Administrator / Customization", functionFamily: "Manufacturing Engineering / Process", aliases: ["cad administrator", "cad administrator / customization", "customization"], headcountWeight: 14 },
  { key: "cad_methods_design_automation_kbe_engineer", name: "CAD Methods / Design Automation (KBE) Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["cad methods", "cad methods / design automation (kbe) engineer", "design automation  engineer", "kbe"], headcountWeight: 14 },
  { key: "plm_business_analyst", name: "PLM Business Analyst", functionFamily: "Manufacturing Engineering / Process", aliases: ["plm business analyst"], headcountWeight: 14 },
  { key: "cad_plm_erp_integration_engineer", name: "CAD/PLM-ERP Integration Engineer", functionFamily: "Manufacturing Engineering / Process", aliases: ["cad", "cad/plm-erp integration engineer", "plm-erp integration engineer"], headcountWeight: 14 },
  { key: "plant_manager", name: "Plant Manager", functionFamily: "Production Operations", aliases: ["plant manager"], headcountWeight: 8, marketTier: "beachhead" },
  { key: "senior_manager", name: "Senior Manager", functionFamily: "Production Operations", aliases: ["department head", "senior manager", "team lead"], headcountWeight: 6, marketTier: "beachhead" },
  { key: "production_value_stream_manager", name: "Production / Value-Stream Manager", functionFamily: "Production Operations", aliases: ["production", "production / value-stream manager", "value-stream manager"], headcountWeight: 8 },
  { key: "shift_supervisor_team_leader", name: "Shift Supervisor / Team Leader", functionFamily: "Production Operations", aliases: ["shift supervisor", "shift supervisor / team leader", "team leader"], headcountWeight: 20 },
  { key: "production_planner_scheduler", name: "Production Planner / Scheduler", functionFamily: "Production Operations", aliases: ["production planner", "production planner / scheduler", "scheduler"], headcountWeight: 14 },
  { key: "machine_operator_cnc_press", name: "Machine Operator (CNC/Press)", functionFamily: "Production Operations", aliases: ["cnc/press", "machine operator", "machine operator (cnc/press)"], headcountWeight: 45 },
  { key: "assembly_technician", name: "Assembly Technician", functionFamily: "Production Operations", aliases: ["assembly technician"], headcountWeight: 45 },
  { key: "paint_shop_technician", name: "Paint Shop Technician", functionFamily: "Production Operations", aliases: ["paint shop technician"], headcountWeight: 45 },
  { key: "battery_cell_module_operator", name: "Battery Cell/Module Operator", functionFamily: "Production Operations", aliases: ["battery cell", "battery cell/module operator", "module operator"], headcountWeight: 45 },
  { key: "kaizen_ci_coordinator", name: "Kaizen / CI Coordinator", functionFamily: "Production Operations", aliases: ["ci coordinator", "kaizen", "kaizen / ci coordinator"], headcountWeight: 14 },
  { key: "ramp_up_coordinator", name: "Ramp-up Coordinator", functionFamily: "Production Operations", aliases: ["ramp-up coordinator"], headcountWeight: 14 },
  { key: "maintenance_technician_mech_elec", name: "Maintenance Technician (Mech/Elec)", functionFamily: "Maintenance & Reliability", aliases: ["maintenance technician", "maintenance technician (mech/elec)", "mech/elec"], headcountWeight: 45 },
  { key: "robot_automation_maintenance_technician", name: "Robot/Automation Maintenance Technician", functionFamily: "Maintenance & Reliability", aliases: ["automation maintenance technician", "robot", "robot/automation maintenance technician"], headcountWeight: 45 },
  { key: "maintenance_planner_scheduler", name: "Maintenance Planner / Scheduler", functionFamily: "Maintenance & Reliability", aliases: ["maintenance planner", "maintenance planner / scheduler", "scheduler"], headcountWeight: 14 },
  { key: "reliability_engineer", name: "Reliability Engineer", functionFamily: "Maintenance & Reliability", aliases: ["reliability engineer"], headcountWeight: 14 },
  { key: "predictive_maintenance_pdm_analyst", name: "Predictive Maintenance (PdM) Analyst", functionFamily: "Maintenance & Reliability", aliases: ["pdm", "predictive maintenance  analyst", "predictive maintenance (pdm) analyst"], headcountWeight: 14 },
  { key: "cmms_administrator", name: "CMMS Administrator", functionFamily: "Maintenance & Reliability", aliases: ["cmms administrator"], headcountWeight: 14 },
  { key: "spare_parts_mro_manager", name: "Spare Parts / MRO Manager", functionFamily: "Maintenance & Reliability", aliases: ["mro manager", "spare parts", "spare parts / mro manager"], headcountWeight: 8 },
  { key: "multi_skilled_mechatronics_technician", name: "Multi-skilled Mechatronics Technician", functionFamily: "Maintenance & Reliability", aliases: ["multi-skilled mechatronics technician"], headcountWeight: 45 },
  { key: "industrial_electrician", name: "Industrial Electrician", functionFamily: "Maintenance & Reliability", aliases: ["industrial electrician"], headcountWeight: 10 },
  { key: "line_technician", name: "Line Technician", functionFamily: "Maintenance & Reliability", aliases: ["line technician"], headcountWeight: 45 },
  { key: "mro_spare_parts_coordinator", name: "MRO / Spare Parts Coordinator", functionFamily: "Maintenance & Reliability", aliases: ["mro", "mro / spare parts coordinator", "spare parts coordinator"], headcountWeight: 14 },
  { key: "condition_monitoring_technician", name: "Condition Monitoring Technician", functionFamily: "Maintenance & Reliability", aliases: ["condition monitoring technician"], headcountWeight: 45 },
  { key: "vibration_analyst_cat_i_iv", name: "Vibration Analyst (Cat I–IV)", functionFamily: "Maintenance & Reliability", aliases: ["cat i–iv", "vibration analyst", "vibration analyst (cat i–iv)"], headcountWeight: 14 },
  { key: "reliability_data_analyst", name: "Reliability Data Analyst", functionFamily: "Maintenance & Reliability", aliases: ["reliability data analyst"], headcountWeight: 14 },
  { key: "quality_manager_plant", name: "Quality Manager (Plant)", functionFamily: "Quality Management", aliases: ["plant", "quality manager", "quality manager (plant)"], headcountWeight: 8 },
  { key: "product_quality_engineer_pqe", name: "Product Quality Engineer (PQE)", functionFamily: "Quality Management", aliases: ["pqe", "product quality engineer", "product quality engineer (pqe)"], headcountWeight: 14 },
  { key: "supplier_quality_engineer_sqe", name: "Supplier Quality Engineer (SQE)", functionFamily: "Quality Management", aliases: ["sqe", "supplier quality engineer", "supplier quality engineer (sqe)"], headcountWeight: 14 },
  { key: "spc_metrology_engineer", name: "SPC / Metrology Engineer", functionFamily: "Quality Management", aliases: ["metrology engineer", "spc", "spc / metrology engineer"], headcountWeight: 14 },
  { key: "incoming_inspection_technician_iqc", name: "Incoming Inspection Technician (IQC)", functionFamily: "Quality Management", aliases: ["incoming inspection technician", "incoming inspection technician (iqc)", "iqc"], headcountWeight: 45 },
  { key: "six_sigma_black_belt", name: "Six Sigma Black Belt", functionFamily: "Quality Management", aliases: ["six sigma black belt"], headcountWeight: 10 },
  { key: "warranty_field_quality_analyst", name: "Warranty / Field Quality Analyst", functionFamily: "Quality Management", aliases: ["field quality analyst", "warranty", "warranty / field quality analyst"], headcountWeight: 14 },
  { key: "quality_auditor_system_process_product", name: "Quality Auditor (System/Process/Product)", functionFamily: "Quality Management", aliases: ["quality auditor", "quality auditor (system/process/product)", "system/process/product"], headcountWeight: 10 },
  { key: "machine_vision_engineer", name: "Machine Vision Engineer", functionFamily: "Quality Management", aliases: ["machine vision engineer"], headcountWeight: 14 },
  { key: "vision_technician_programmer", name: "Vision Technician / Programmer", functionFamily: "Quality Management", aliases: ["programmer", "vision technician", "vision technician / programmer"], headcountWeight: 45 },
  { key: "aoi_engineer", name: "AOI Engineer", functionFamily: "Quality Management", aliases: ["aoi engineer"], headcountWeight: 14 },
  { key: "vision_integration_engineer", name: "Vision Integration Engineer", functionFamily: "Quality Management", aliases: ["vision integration engineer"], headcountWeight: 14 },
  { key: "automated_ndt_engineer", name: "Automated NDT Engineer", functionFamily: "Quality Management", aliases: ["automated ndt engineer"], headcountWeight: 14 },
  { key: "quality_data_systems_engineer", name: "Quality Data Systems Engineer", functionFamily: "Quality Management", aliases: ["quality data systems engineer"], headcountWeight: 14 },
  { key: "in_process_end_of_line_test_engineer", name: "In-Process / End-of-Line Test Engineer", functionFamily: "Quality Management", aliases: ["end-of-line test engineer", "in-process", "in-process / end-of-line test engineer"], headcountWeight: 14 },
  { key: "strategic_buyer_commodity_manager", name: "Strategic Buyer / Commodity Manager", functionFamily: "Supply Chain & Procurement", aliases: ["commodity manager", "strategic buyer", "strategic buyer / commodity manager"], headcountWeight: 14 },
  { key: "program_buyer", name: "Program Buyer", functionFamily: "Supply Chain & Procurement", aliases: ["program buyer"], headcountWeight: 14 },
  { key: "procurement_specialist_p2p", name: "Procurement Specialist (P2P)", functionFamily: "Supply Chain & Procurement", aliases: ["p2p", "procurement specialist", "procurement specialist (p2p)"], headcountWeight: 14 },
  { key: "supplier_development_engineer", name: "Supplier Development Engineer", functionFamily: "Supply Chain & Procurement", aliases: ["supplier development engineer"], headcountWeight: 14 },
  { key: "material_planner_mrp", name: "Material Planner (MRP)", functionFamily: "Supply Chain & Procurement", aliases: ["material planner", "material planner (mrp)", "mrp"], headcountWeight: 14 },
  { key: "supply_chain_planner", name: "Supply Chain Planner", functionFamily: "Supply Chain & Procurement", aliases: ["supply chain planner"], headcountWeight: 14 },
  { key: "demand_planner_s_op", name: "Demand Planner (S&OP)", functionFamily: "Supply Chain & Procurement", aliases: ["demand planner", "demand planner (s&op)", "s&op"], headcountWeight: 14 },
  { key: "supplier_risk_resilience_analyst", name: "Supplier Risk / Resilience Analyst", functionFamily: "Supply Chain & Procurement", aliases: ["resilience analyst", "supplier risk", "supplier risk / resilience analyst"], headcountWeight: 14 },
  { key: "va_ve_cost_reduction_buyer", name: "VA/VE Cost Reduction Buyer", functionFamily: "Supply Chain & Procurement", aliases: ["va", "va/ve cost reduction buyer", "ve cost reduction buyer"], headcountWeight: 14 },
  { key: "localization_planner", name: "Localization Planner", functionFamily: "Supply Chain & Procurement", aliases: ["localization planner"], headcountWeight: 14 },
  { key: "logistics_manager_plant", name: "Logistics Manager (Plant)", functionFamily: "Logistics & Material Flow", aliases: ["logistics manager", "logistics manager (plant)", "plant"], headcountWeight: 8 },
  { key: "inbound_outbound_coordinator", name: "Inbound/Outbound Coordinator", functionFamily: "Logistics & Material Flow", aliases: ["inbound", "inbound/outbound coordinator", "outbound coordinator"], headcountWeight: 14 },
  { key: "warehouse_supervisor", name: "Warehouse Supervisor", functionFamily: "Logistics & Material Flow", aliases: ["warehouse supervisor"], headcountWeight: 20 },
  { key: "material_handler_forklift_operator", name: "Material Handler / Forklift Operator", functionFamily: "Logistics & Material Flow", aliases: ["forklift operator", "material handler", "material handler / forklift operator"], headcountWeight: 45 },
  { key: "packaging_engineer", name: "Packaging Engineer", functionFamily: "Logistics & Material Flow", aliases: ["packaging engineer"], headcountWeight: 14 },
  { key: "sequencing_jis_planner", name: "Sequencing (JIS) Planner", functionFamily: "Logistics & Material Flow", aliases: ["jis", "sequencing  planner", "sequencing (jis) planner"], headcountWeight: 14 },
  { key: "transport_network_analyst", name: "Transport Network Analyst", functionFamily: "Logistics & Material Flow", aliases: ["transport network analyst"], headcountWeight: 14 },
  { key: "customs_trade_compliance_specialist", name: "Customs & Trade Compliance Specialist", functionFamily: "Logistics & Material Flow", aliases: ["customs & trade compliance specialist"], headcountWeight: 14 },
  { key: "3pl_carrier_contract_manager", name: "3PL / Carrier Contract Manager", functionFamily: "Logistics & Material Flow", aliases: ["3pl", "3pl / carrier contract manager", "carrier contract manager"], headcountWeight: 8 },
  { key: "agv_amr_fleet_engineer", name: "AGV/AMR Fleet Engineer", functionFamily: "Logistics & Material Flow", aliases: ["agv", "agv/amr fleet engineer", "amr fleet engineer"], headcountWeight: 14 },
  { key: "amr_application_engineer", name: "AMR Application Engineer", functionFamily: "Logistics & Material Flow", aliases: ["amr application engineer"], headcountWeight: 14 },
  { key: "as_rs_engineer", name: "AS/RS Engineer", functionFamily: "Logistics & Material Flow", aliases: ["as", "as/rs engineer", "rs engineer"], headcountWeight: 14 },
  { key: "wms_wcs_integration_engineer", name: "WMS/WCS Integration Engineer", functionFamily: "Logistics & Material Flow", aliases: ["wcs integration engineer", "wms", "wms/wcs integration engineer"], headcountWeight: 14 },
  { key: "intralogistics_controls_engineer", name: "Intralogistics Controls Engineer", functionFamily: "Logistics & Material Flow", aliases: ["intralogistics controls engineer"], headcountWeight: 14 },
  { key: "warehouse_automation_technician", name: "Warehouse Automation Technician", functionFamily: "Logistics & Material Flow", aliases: ["warehouse automation technician"], headcountWeight: 45 },
  { key: "amr_safety_engineer", name: "AMR Safety Engineer", functionFamily: "Logistics & Material Flow", aliases: ["amr safety engineer"], headcountWeight: 14 },
  { key: "robot_programmer", name: "Robot Programmer", functionFamily: "Robotics & Automation Cells", aliases: ["robot programmer"], headcountWeight: 14 },
  { key: "robotics_technician", name: "Robotics Technician", functionFamily: "Robotics & Automation Cells", aliases: ["robotics technician"], headcountWeight: 45 },
  { key: "robot_cell_designer", name: "Robot Cell Designer", functionFamily: "Robotics & Automation Cells", aliases: ["robot cell designer"], headcountWeight: 10 },
  { key: "cobot_application_engineer", name: "Cobot Application Engineer", functionFamily: "Robotics & Automation Cells", aliases: ["cobot application engineer"], headcountWeight: 14 },
  { key: "eoat_engineer", name: "EOAT Engineer", functionFamily: "Robotics & Automation Cells", aliases: ["eoat engineer"], headcountWeight: 14 },
  { key: "robot_welding_engineer", name: "Robot Welding Engineer", functionFamily: "Robotics & Automation Cells", aliases: ["robot welding engineer"], headcountWeight: 14 },
  { key: "controls_engineer_plc_programmer", name: "Controls Engineer / PLC Programmer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["controls engineer", "controls engineer / plc programmer", "plc programmer"], headcountWeight: 14 },
  { key: "controls_architect_standards_engineer", name: "Controls Architect / Standards Engineer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["controls architect", "controls architect / standards engineer", "standards engineer"], headcountWeight: 14 },
  { key: "motion_control_engineer", name: "Motion Control Engineer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["motion control engineer"], headcountWeight: 14 },
  { key: "functional_safety_plc_engineer", name: "Functional Safety PLC Engineer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["functional safety plc engineer"], headcountWeight: 14 },
  { key: "hmi_developer", name: "HMI Developer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["hmi developer"], headcountWeight: 14 },
  { key: "process_automation_engineer_batch", name: "Process Automation Engineer (Batch)", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["batch", "process automation engineer", "process automation engineer (batch)"], headcountWeight: 14 },
  { key: "industrial_network_specialist", name: "Industrial Network Specialist", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["industrial network specialist"], headcountWeight: 14 },
  { key: "instrumentation_controls_technician", name: "Instrumentation & Controls Technician", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["instrumentation & controls technician"], headcountWeight: 45 },
  { key: "commissioning_engineer", name: "Commissioning Engineer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["commissioning engineer"], headcountWeight: 14 },
  { key: "mes_engineer", name: "MES Engineer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["mes engineer"], headcountWeight: 14 },
  { key: "mes_integrator_developer", name: "MES Integrator / Developer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["developer", "mes integrator", "mes integrator / developer"], headcountWeight: 14 },
  { key: "scada_developer", name: "SCADA Developer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["scada developer"], headcountWeight: 14 },
  { key: "historian_engineer", name: "Historian Engineer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["historian engineer"], headcountWeight: 14 },
  { key: "scada_historian_administrator", name: "SCADA/Historian Administrator", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["historian administrator", "scada", "scada/historian administrator"], headcountWeight: 14 },
  { key: "mes_support_analyst", name: "MES Support Analyst", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["mes support analyst"], headcountWeight: 14 },
  { key: "manufacturing_systems_architect", name: "Manufacturing Systems Architect", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["manufacturing systems architect"], headcountWeight: 8 },
  { key: "bop_mes_integration_engineer", name: "BOP-MES Integration Engineer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["bop-mes integration engineer"], headcountWeight: 14 },
  { key: "production_it_ot_plc_scada_engineer", name: "Production IT / OT (PLC-SCADA) Engineer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["ot  engineer", "plc-scada", "production it", "production it / ot (plc-scada) engineer"], headcountWeight: 14 },
  { key: "manufacturing_analytics_data_engineer", name: "Manufacturing Analytics / Data Engineer", functionFamily: "Controls & Automation (PLC/SCADA/MES)", aliases: ["data engineer", "manufacturing analytics", "manufacturing analytics / data engineer"], headcountWeight: 14 },
  { key: "iiot_architect", name: "IIoT Architect", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["iiot architect"], headcountWeight: 8 },
  { key: "edge_computing_engineer", name: "Edge Computing Engineer", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["edge computing engineer"], headcountWeight: 14 },
  { key: "ot_data_engineer", name: "OT Data Engineer", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["ot data engineer"], headcountWeight: 14 },
  { key: "protocol_gateway_specialist", name: "Protocol Gateway Specialist", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["protocol gateway specialist"], headcountWeight: 14 },
  { key: "sensor_integration_engineer", name: "Sensor Integration Engineer", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["sensor integration engineer"], headcountWeight: 14 },
  { key: "ot_infrastructure_engineer", name: "OT Infrastructure Engineer", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["ot infrastructure engineer"], headcountWeight: 14 },
  { key: "ics_ot_security_engineer", name: "ICS/OT Security Engineer", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["ics", "ics/ot security engineer", "ot security engineer"], headcountWeight: 14 },
  { key: "ot_security_architect", name: "OT Security Architect", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["ot security architect"], headcountWeight: 8 },
  { key: "ot_soc_analyst", name: "OT SOC Analyst", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["ot soc analyst"], headcountWeight: 14 },
  { key: "ot_vulnerability_patch_manager", name: "OT Vulnerability & Patch Manager", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["ot vulnerability & patch manager"], headcountWeight: 8 },
  { key: "secure_remote_access_specialist", name: "Secure Remote Access Specialist", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["secure remote access specialist"], headcountWeight: 14 },
  { key: "plant_it_infrastructure_engineer", name: "Plant IT Infrastructure Engineer", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["plant it infrastructure engineer"], headcountWeight: 14 },
  { key: "ot_asset_configuration_manager", name: "OT Asset & Configuration Manager", functionFamily: "Industrial IoT, Edge & OT Security", aliases: ["ot asset & configuration manager"], headcountWeight: 8 },
  { key: "manufacturing_data_scientist", name: "Manufacturing Data Scientist", functionFamily: "Data Science, Digital Twin & Plant Analytics", aliases: ["manufacturing data scientist"], headcountWeight: 14 },
  { key: "oee_performance_analytics_engineer", name: "OEE / Performance Analytics Engineer", functionFamily: "Data Science, Digital Twin & Plant Analytics", aliases: ["oee", "oee / performance analytics engineer", "performance analytics engineer"], headcountWeight: 14 },
  { key: "digital_twin_engineer", name: "Digital Twin Engineer", functionFamily: "Data Science, Digital Twin & Plant Analytics", aliases: ["digital twin engineer"], headcountWeight: 14 },
  { key: "simulation_engineer_des", name: "Simulation Engineer (DES)", functionFamily: "Data Science, Digital Twin & Plant Analytics", aliases: ["des", "simulation engineer", "simulation engineer (des)"], headcountWeight: 14 },
  { key: "golden_batch_process_analytics_engineer", name: "Golden Batch / Process Analytics Engineer", functionFamily: "Data Science, Digital Twin & Plant Analytics", aliases: ["golden batch", "golden batch / process analytics engineer", "process analytics engineer"], headcountWeight: 14 },
  { key: "edge_ml_engineer", name: "Edge ML Engineer", functionFamily: "Data Science, Digital Twin & Plant Analytics", aliases: ["edge ml engineer"], headcountWeight: 14 },
  { key: "analytics_platform_engineer", name: "Analytics Platform Engineer", functionFamily: "Data Science, Digital Twin & Plant Analytics", aliases: ["analytics platform engineer"], headcountWeight: 14 },
  { key: "energy_sustainability_analyst", name: "Energy & Sustainability Analyst", functionFamily: "Data Science, Digital Twin & Plant Analytics", aliases: ["energy & sustainability analyst"], headcountWeight: 14 },
  { key: "sales_director", name: "Sales Director", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["sales director"], headcountWeight: 4 },
  { key: "key_account_fleet_sales_manager", name: "Key Account / Fleet Sales Manager", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["fleet sales manager", "key account", "key account / fleet sales manager"], headcountWeight: 8 },
  { key: "dealer_network_development_manager", name: "Dealer Network Development Manager", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["dealer network development manager"], headcountWeight: 8 },
  { key: "product_manager_lineup_pricing", name: "Product Manager (Lineup & Pricing)", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["lineup & pricing", "product manager", "product manager (lineup & pricing)"], headcountWeight: 8 },
  { key: "brand_marketing_manager", name: "Brand Marketing Manager", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["brand marketing manager"], headcountWeight: 8 },
  { key: "digital_marketing_specialist", name: "Digital Marketing Specialist", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["digital marketing specialist"], headcountWeight: 14 },
  { key: "market_research_competitive_analyst", name: "Market Research / Competitive Analyst", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["competitive analyst", "market research", "market research / competitive analyst"], headcountWeight: 14 },
  { key: "sales_operations_incentives_analyst", name: "Sales Operations / Incentives Analyst", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["incentives analyst", "sales operations", "sales operations / incentives analyst"], headcountWeight: 14 },
  { key: "crm_manager", name: "CRM Manager", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["crm manager"], headcountWeight: 8 },
  { key: "pr_communications_manager", name: "PR / Communications Manager", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["communications manager", "pr", "pr / communications manager"], headcountWeight: 8 },
  { key: "aftersales_director", name: "Aftersales Director", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["aftersales director"], headcountWeight: 4 },
  { key: "parts_catalogue_specialist", name: "Parts Catalogue Specialist", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["parts catalogue specialist"], headcountWeight: 14 },
  { key: "spare_parts_planner", name: "Spare Parts Planner", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["spare parts planner"], headcountWeight: 14 },
  { key: "parts_pricing_analyst", name: "Parts Pricing Analyst", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["parts pricing analyst"], headcountWeight: 14 },
  { key: "warranty_administrator_analyst", name: "Warranty Administrator / Analyst", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["analyst", "warranty administrator", "warranty administrator / analyst"], headcountWeight: 14 },
  { key: "tsb_engineer", name: "TSB Engineer", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["tsb engineer"], headcountWeight: 14 },
  { key: "field_service_engineer", name: "Field Service Engineer", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["field service engineer"], headcountWeight: 14 },
  { key: "service_training_instructor", name: "Service Training Instructor", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["service training instructor"], headcountWeight: 10 },
  { key: "dealer_technical_support_hotline", name: "Dealer Technical Support (Hotline)", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["dealer technical support", "dealer technical support (hotline)", "hotline"], headcountWeight: 10 },
  { key: "remanufacturing_engineer", name: "Remanufacturing Engineer", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["remanufacturing engineer"], headcountWeight: 14 },
  { key: "connected_services_telematics_engineer", name: "Connected Services / Telematics Engineer", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["connected services", "connected services / telematics engineer", "telematics engineer"], headcountWeight: 14 },
  { key: "customer_care_contact_center_agent", name: "Customer Care / Contact Center Agent", functionFamily: "Sales, Marketing & Aftermarket", aliases: ["contact center agent", "customer care", "customer care / contact center agent"], headcountWeight: 10 },
  { key: "controller_fp_a_analyst", name: "Controller / FP&A Analyst", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["controller", "controller / fp&a analyst", "fp&a analyst"], headcountWeight: 14 },
  { key: "plant_controller", name: "Plant Controller", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["plant controller"], headcountWeight: 10 },
  { key: "program_finance_manager", name: "Program Finance Manager", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["program finance manager"], headcountWeight: 8 },
  { key: "cost_accountant", name: "Cost Accountant", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["cost accountant"], headcountWeight: 10 },
  { key: "treasury_analyst", name: "Treasury Analyst", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["treasury analyst"], headcountWeight: 14 },
  { key: "internal_auditor", name: "Internal Auditor", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["internal auditor"], headcountWeight: 10 },
  { key: "tax_specialist", name: "Tax Specialist", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["tax specialist"], headcountWeight: 14 },
  { key: "investor_relations_manager", name: "Investor Relations Manager", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["investor relations manager"], headcountWeight: 8 },
  { key: "hr_business_partner", name: "HR Business Partner", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["hr business partner"], headcountWeight: 10 },
  { key: "talent_acquisition_specialist", name: "Talent Acquisition Specialist", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["talent acquisition specialist"], headcountWeight: 14 },
  { key: "technical_trainer_l_d", name: "Technical Trainer (L&D)", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["l&d", "technical trainer", "technical trainer (l&d)"], headcountWeight: 10 },
  { key: "hris_payroll_analyst", name: "HRIS / Payroll Analyst", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["hris", "hris / payroll analyst", "payroll analyst"], headcountWeight: 14 },
  { key: "enterprise_architect_erp_core", name: "Enterprise Architect (ERP Core)", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["enterprise architect", "enterprise architect (erp core)", "erp core"], headcountWeight: 8 },
  { key: "erp_mes_functional_analyst", name: "ERP / MES Functional Analyst", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["erp", "erp / mes functional analyst", "mes functional analyst"], headcountWeight: 14 },
  { key: "data_engineer_bi_analyst", name: "Data Engineer / BI Analyst", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["bi analyst", "data engineer", "data engineer / bi analyst"], headcountWeight: 14 },
  { key: "it_service_desk_field_tech", name: "IT Service Desk / Field Tech", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["field tech", "it service desk", "it service desk / field tech"], headcountWeight: 10 },
  { key: "commercial_counsel", name: "Commercial Counsel", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["commercial counsel"], headcountWeight: 4 },
  { key: "ip_counsel", name: "IP Counsel", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["ip counsel"], headcountWeight: 4 },
  { key: "product_liability_counsel", name: "Product Liability Counsel", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["product liability counsel"], headcountWeight: 4 },
  { key: "compliance_officer_export_controls", name: "Compliance Officer (Export Controls)", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["compliance officer", "compliance officer (export controls)", "export controls"], headcountWeight: 4 },
  { key: "facilities_manager", name: "Facilities Manager", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["facilities manager"], headcountWeight: 8 },
  { key: "utilities_energy_engineer", name: "Utilities / Energy Engineer", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["energy engineer", "utilities", "utilities / energy engineer"], headcountWeight: 14 },
  { key: "ehs_manager", name: "EHS Manager", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["ehs manager"], headcountWeight: 8 },
  { key: "safety_engineer", name: "Safety Engineer", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["safety engineer"], headcountWeight: 14 },
  { key: "environmental_engineer", name: "Environmental Engineer", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["environmental engineer"], headcountWeight: 14 },
  { key: "ergonomist", name: "Ergonomist", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["ergonomist"], headcountWeight: 10 },
  { key: "sustainability_esg_manager", name: "Sustainability / ESG Manager", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["esg manager", "sustainability", "sustainability / esg manager"], headcountWeight: 8 },
  // ── Cross-cutting roles (hand-curated, not in the OEM engineering sweep) ──
  { key: "general_office_staff", name: "Office Worker (General)", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["office worker", "general office", "administrative staff", "office worker (general)"], headcountWeight: 40 },
  { key: "executive_assistant", name: "Executive Assistant", functionFamily: "Business Services (Finance / HR / IT / Legal / EHS)", aliases: ["ea", "exec assistant"], headcountWeight: 6 },
];
